[package]
name = "util"
version = "0.1.0"
edition = "2021"

[features]
testing = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(automock)'] }

[dependencies]
thiserror.workspace = true
tracing.workspace = true
camino.workspace = true
mockall.workspace = true
nix.workspace = true

[dependencies.config]
path = "../config"
