network_interface = "eth0"
run_path = "/srv/runners"
github_pat = "ghp_1234567890"
github_org = "matsimitsu"

[lvm]
volume_group = "runners"
thin_pool = "pool"

[[roles]]
name = "default"
rootfs_image = "/var/lib/runners/images/ubuntu-22.04-runner.img"
kernel_image = "/var/lib/runners/kernels/vmlinux-5.10"
cpus = 4
memory_size = 4
cache_size = 20
instance_count = 4
labels = ["ubuntu-22.04"]
